import "./globals.css";
import '@fortawesome/fontawesome-free/css/all.min.css';
import Popup from "./popup";


export const metadata = {
  title: "AlgorithmX | Next-Gen Product Development And Disruptive Market Positioning",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
          integrity="sha384-..."
          crossOrigin="anonymous"
        />
      </head>
      <body suppressHydrationWarning={true}>
        {children}
        
      </body>
      
    </html>
  );
}
